SetPrivateProfileString('Multiplayer','Enable Chat Menu','1')
SetPrivateProfileString('Multiplayer','Disable Banters','1')
SetPrivateProfileString('Game Options','Show Learnable Spells','1')
SetPrivateProfileString('Game Options','Tutorial State','1')
SetPrivateProfileString('Game Options','Hotkeys On Tooltips','1')
SetPrivateProfileString('Game Options','Memory Level','1')
SetPrivateProfileString('Game Options','Color Circles','1')
SetPrivateProfileString('Game Options','Auto Pause State','0')
SetPrivateProfileString('Game Options','Ranged Weapon Switching','0')
SetPrivateProfileString('Game Options','3E Thief Sneak Attack','1')
SetPrivateProfileString('Game Options','No Difficulty Based XP Bonus','1')
SetPrivateProfileString('Game Options','Weather','1')
SetPrivateProfileString('Game Options','Effect Text Level','63')
SetPrivateProfileString('Game Options','Render Actions','0')
SetPrivateProfileString('Game Options','Subtitles','1')
SetPrivateProfileString('Game Options','Nightmare Bonus XP','0')
SetPrivateProfileString('Game Options','Message Box Top','96')
SetPrivateProfileString('Game Options','HP Over Head','0')
SetPrivateProfileString('Game Options','Environmental Audio','1')
SetPrivateProfileString('Game Options','Over Confirm Everything','0')
SetPrivateProfileString('Game Options','GUI Feedback Level','5')
SetPrivateProfileString('Game Options','Terrain Hugging','0')
SetPrivateProfileString('Game Options','Attack Sounds','1')
SetPrivateProfileString('Game Options','Locator Feedback Level','3')
SetPrivateProfileString('Game Options','Confirm Dialog','0')
SetPrivateProfileString('Game Options','Selection Sounds Frequency','3')
SetPrivateProfileString('Game Options','Render Explored Map','0')
SetPrivateProfileString('Game Options','Cleric Ranger Spells','1')
SetPrivateProfileString('Game Options','Show Message Box Hint','1')
SetPrivateProfileString('Game Options','Tiles Precache Percent','100')
SetPrivateProfileString('Game Options','Keyboard Scroll Speed','37')
SetPrivateProfileString('Game Options','Difficulty Level','2')
SetPrivateProfileString('Game Options','Suppress Extra Difficulty Damage','0')
SetPrivateProfileString('Game Options','Show Character HP','1')
SetPrivateProfileString('Game Options','Last Save','000000000-Auto-Save')
SetPrivateProfileString('Game Options','Duplicate Floating Text','1')
SetPrivateProfileString('Game Options','Always Dither','1')
SetPrivateProfileString('Game Options','Area Effects Density','100')
SetPrivateProfileString('Game Options','Bored Timeout','3000')
SetPrivateProfileString('Game Options','Heal Party on Rest','0')
SetPrivateProfileString('Game Options','Auto Pause Center','1')
SetPrivateProfileString('Game Options','Journal Popups','1')
SetPrivateProfileString('Game Options','Maximum HP','0')
SetPrivateProfileString('Game Options','Filter Games','1')
SetPrivateProfileString('Game Options','Command Sounds Frequency','2')
SetPrivateProfileString('Game Options','Render Travel Regions','0')
SetPrivateProfileString('Game Options','Infravision','1')
SetPrivateProfileString('Game Options','Extra Feedback','0')
SetPrivateProfileString('Game Options','Mouse Scroll Speed','36')
SetPrivateProfileString('Game Options','Footsteps','1')
SetPrivateProfileString('Game Options','All Learn Spell Info','0')
SetPrivateProfileString('Game Options','Critical Hit Screen Shake','1')
SetPrivateProfileString('Game Options','Quick Item Mapping','1')
SetPrivateProfileString('Game Options','Nightmare Bonus Gold','0')
SetPrivateProfileString('Game Options','Combat UI','1')
SetPrivateProfileString('Game Options','Pausing Map','0')
SetPrivateProfileString('Game Options','Classic Selection Circles','0')
SetPrivateProfileString('Graphics','Scale UI','1')
SetPrivateProfileString('Graphics','Use Character Highlights','1')
SetPrivateProfileString('Graphics','vendor','NVIDIA Corporation')
SetPrivateProfileString('Graphics','Use Sprite Outlines','1')
SetPrivateProfileString('Graphics','Backend','0')
SetPrivateProfileString('Graphics','version','OpenGL version 4.4.0 NVIDIA 344.11 - build XXXX')
SetPrivateProfileString('Graphics','Show Black Space','1')
SetPrivateProfileString('Graphics','Greyscale On Pause','0')
SetPrivateProfileString('Graphics','Zoom Lock','0')
SetPrivateProfileString('Graphics','Use Nearest Neighbour Scaling','0')
SetPrivateProfileString('Graphics','Hardware Mouse Cursor','1')
SetPrivateProfileString('Graphics','renderer','GeForce GTX 750 Ti/PCIe/SSE2')
SetPrivateProfileString('Lua Edit','String3',[[ C:SetCurrentXP('161000')]])
SetPrivateProfileString('Lua Edit','String9',[[ C:SetCurrentXP('2000')]])
SetPrivateProfileString('Lua Edit','String6',[[ C:SetCurrentXP('161000')]])
SetPrivateProfileString('Lua Edit','String2',[[C:SetCurrentXP('161000')]])
SetPrivateProfileString('Lua Edit','String4',[[C:SetCurrentXP('2000')]])
SetPrivateProfileString('Lua Edit','String8',[[C:SetCurrentXP('2000')]])
SetPrivateProfileString('Lua Edit','String7',[[C:SetCurrentXP('161000')]])
SetPrivateProfileString('Lua Edit','String1',[[ C:SetCurrentXP('32000')]])
SetPrivateProfileString('Lua Edit','String5',[[ C:SetCurrentXP('161000')]])
SetPrivateProfileString('Lua Edit','String0',[[C:SetCurrentXP('161000')]])
SetPrivateProfileString('Program Options','Translucent Shadows','1')
SetPrivateProfileString('Program Options','Path Search Nodes','32000')
SetPrivateProfileString('Program Options','Drop Capitals','1')
SetPrivateProfileString('Program Options','Volume SFX','82')
SetPrivateProfileString('Program Options','Double Byte Character Support','0')
SetPrivateProfileString('Program Options','Sprite Mirror','0')
SetPrivateProfileString('Program Options','Disable Cosmetic Attacks','0')
SetPrivateProfileString('Program Options','Volume Ambients','28')
SetPrivateProfileString('Program Options','Volume Music','30')
SetPrivateProfileString('Program Options','Active Campaign','0')
SetPrivateProfileString('Program Options','Font Name','')
SetPrivateProfileString('Program Options','Display Subtitles','0')
SetPrivateProfileString('Program Options','Maximum Frame Rate','30')
SetPrivateProfileString('Program Options','Tooltips','60')
SetPrivateProfileString('Program Options','Cloud Saves Enabled','0')
SetPrivateProfileString('Program Options','Volume Movie','92')
SetPrivateProfileString('Program Options','3D Acceleration','1')
SetPrivateProfileString('Program Options','Debug Mode','1')
SetPrivateProfileString('Program Options','Volume Voices','100')
SetPrivateProfileString('Language','Text','en_US')
SetPrivateProfileString('Fonts','ja_JP','MEIRYO')
SetPrivateProfileString('Fonts','ko_KR','NANUM')
SetPrivateProfileString('Fonts','ru_RU','PTSERIF')
SetPrivateProfileString('Fonts','Zoom','112')
SetPrivateProfileString('Fonts','zh_CN','SIMSUN')
SetPrivateProfileString('Fonts','uk_UA','PERMIAN')
SetPrivateProfileString('Window','Full Screen','1')
SetPrivateProfileString('Window','Maximized','0')
SetPrivateProfileString('MOVIES','RESTINN','1')
SetPrivateProfileString('MOVIES','LOGO','1')
SetPrivateProfileString('MOVIES','REST','1')
SetPrivateProfileString('MOVIES','INTRO','1')
SetPrivateProfileString('MOVIES','BLACKPIT','1')
SetPrivateProfileString('MOVIES','DEATHAND','1')
SetPrivateProfileString('MOVIES','FRARMINN','1')
