IF
	NumInPartyGT(%party_size%)
    CheckStatGT(%object%,%xp1%,XP)
    CheckStat(%object%,%lvl%,LEVEL)
	CheckStat(%object%,0,LEVEL2)
THEN
	RESPONSE #100
		ApplySpellRES("SETXP1%lvl%",%object%)
		Continue()
END


IF
    NumInPartyGT(%party_size%)
	CheckStatGT(%object%,%xp2%,XP)
    CheckStat(%object%,%lvl%,LEVEL)
	!CheckStat(%object%,0,LEVEL2)
THEN
	RESPONSE #100
		ApplySpellRES("SETXP2%lvl%",%object%)
		Continue()
END



