DEFINE_PATCH_FUNCTION ~MAKE_ALWAYS_CASTABLE~
//makes spell always castable (i.e. when silenced or in dead/wild magic zone when silenced or on invisible targets)
    BEGIN
        READ_BYTE 0x0019 flag2
        READ_BYTE 0x001A flag4    
        SET flag2 = flag2 BOR 0b11000000
        SET flag4 = flag4 BOR 0b00000011
        WRITE_BYTE 0x0019 flag2
        WRITE_BYTE 0x001A flag4
    END
    
    